### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by bes** [taehwanno/warnings-to-errors-webpack-plugin#58]
Nice plugin! I am using a webpack-config.ts (TypeScript for Webpack).

Would it be possible to add TypeScript types to this project?

If possible, I would prefer if the types are added to the repo directly and not to the `@types/`-project.

Do you take contributions? In that case I might be able to do it.

**Comment by bes** [comment]
As an example https://github.com/jantimon/html-webpack-plugin has typings.

**Comment by taehwanno** [comment]
Thanks. contributions welcome :)

**Comment by bes** [comment]
Awaiting review.
